---

  - name: apt-get update
    apt:
      update_cache: yes
    when:
      - ansible_distribution == "Ubuntu"

  - name: install RedHat packages
    yum: name={{ item }} state=latest
    with_items: "{{ redhat_packages }}"
    when:
      - ansible_distribution == "RedHat"

  - name: install Ubuntu packages
    apt: name={{ item }} state=latest
    with_items: "{{ ubuntu_packages }}"
    when:
      - ansible_distribution == "Ubuntu"

  - name: Create parts and var directories
    file:
      path: "{{ svc_home }}/sites/{{ svc_user }}/{{ item }}"
      state: directory
    with_items:
      - parts
      - var/log
    become: yes
    become_user: "{{ svc_user }}"

  - name: Copy in new /etc/hosts file to allow port forwarding with Apache in Vagrant
    copy:
      src: templates/hosts_template
      dest: "/etc/hosts"
      owner: root
      group: root
    when: env == "dev"
